[database]
engine = "sqlite"
driver = ""
user_name = ""
password = ""
database_name = "db.sqlite3"

[backend_integration]
enable = false
backend_type = "office"
backend_connection = "127.0.0.1:9999"

[main_display]
width = 1024
height = 768

[customer_display]
enable = true
width = 1024
height = 768

[design_files]
main_display.login = "sale.toml"
customer_display.login = "login.toml"
main_display.menu = "menu.toml"
customer_display.menu = "menu.toml"
main_display.sale = "sale.toml"
customer_display.sale = "sale.toml"