[settings]
name = "Login"
functionality = "login"
login_required = false
toolbar = false
statusbar = false
background_color = 0x3268A8
foreground_color = 0x000000
width = 1280
height = 640

[textbox]
caption = "User Name"
input_type = "alphanumeric"
alignment = "left"
background_color = 0xFFFFFF
foreground_color = 0x000000
width = 100
height = 50
location_x = 0
location_y = 0

[password_textbox]
caption = "Password"
input_type = "password"
background_color = 0xFFFFFF
foreground_color = 0x000000
width = 100
height = 50
location_x = 0
location_y = 0

[submit_button]
caption = "Login"
function = "login"
background_color = 0xFFFFFF
foreground_color = 0x000000
width = 100
height = 50
location_x = 0
location_y = 0
