[settings]
name = "Login"
functionality = "LOGIN"
login_required = false
toolbar = false
statusbar = false
background_color = 0x3268A8
foreground_color = 0x000000
width = 1024
height = 768

[[design]]
type = "textbox"
caption = "User Name"
place_holder = "User Name"
input_type = "alphanumeric"
field_name = "user_name"
alignment = "center"
font_size = 20
background_color = 0xFFFFFF
foreground_color = 0x000000
width = 300
height = 50
location_x = 362
location_y = 150
use_keyboard = true

[[design]]
type = "textbox"
caption = "Password"
place_holder = "Password"
input_type = "password"
field_name = "password"
alignment = "center"
font_size = 20
background_color = 0xFFFFFF
foreground_color = 0x000000
width = 300
height = 50
location_x = 362
location_y = 225
use_keyboard = true


[[design]]
type = "button"
caption = "Login"
function = "LOGIN"
background_color = 0x003366
foreground_color = 0xFFFFFF
width = 250
height = 50
location_x = 387
location_y = 300

[[design]]
type = "button"
caption = "Exit"
function = "EXIT_APPLICATION"
background_color = 0xFF0000
foreground_color = 0xFFFFFF
width = 200
height = 50
location_x = 412
location_y = 400
