[settings]
name = "Login"
functionality = "LOGIN"
login_required = false
toolbar = false
statusbar = false
background_color = 0x3268A8
foreground_color = 0x000000
width = 1024
height = 768

[[design]]
type = "button"
caption = "Login"
function = "LOGIN"
background_color = 0x003366
foreground_color = 0xFFFFFF
width = 200
height = 50
location_x = 450
location_y = 400

[[design]]
type = "button"
caption = "Exit"
function = "EXIT_APPLICATION"
background_color = 0xFF0000
foreground_color = 0xFFFFFF
width = 200
height = 50
location_x = 450
location_y = 500
