[settings]
name = "Sale"
functionality = "SALE"
login_required = true
toolbar = true
statusbar = true
background_color = 0x3268A8
foreground_color = 0x000000
width = 1024
height = 768

[toolbar_settings]
button.back = { caption = "Back", image = "back.png" }

[[design]]
type = "button"
caption = "Back"
function = "BACK"
background_color = 0xFF0000
foreground_color = 0xFFFFFF
width = 200
height = 50
location_x = 412
location_y = 200

[[design]]
type = "button"
caption = "FOOD"
name = "DEPARTMENT1"
function = "SALE_DEPARTMENT"
background_color = 0xFF0000
foreground_color = 0xFFFFFF
width = 100
height = 50
location_x = 1
location_y = 400

[[design]]
type = "numpad"
caption = "NumPad"
function = "PLU"
background_color = 0x778D45
foreground_color = 0xFFFFFF
width = 200
height = 50
location_x = 412
location_y = 200
